GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiVTJGc2RHVmtYMTlIU3ZyYmp0VVFsU2tJcDhRRC9qdVYyRWtud0FXTUVSQVhpOXFabC9QYzI4b1EzblZxbnkwbktMdFcrZkJZYng2TEoxOEtYNmlZUjZad1lTQUJuYkphdFRjdUhsbDV2VnMrZEd6WVRrUzlraGp6L0RvcllSMi8xbWFzWnZ6OWRpVDR0c2xmK2JwTkJBPT0iLCJpYXQiOjE3NDQzMDkxNjksImV4cCI6MTc0NDM5NTU2OX0.GvfrVKWyJWkOdawuwjq9D0r5iICedpsx0BeB8ObFD2c

###
GET http://localhost:3000/users/2b42c13e-4b1c-4baf-b212-b1b2cae9e923
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiVTJGc2RHVmtYMS9XN2hrSnJhSDRLUXk5YXVnZk83ay96eG9yREJCK3MxNzk2dXVYTjJ1Vk9oYVJrQzBVVXZmSUJ5aDBXZFNHbDZ5dm14TlNZTFJZODZuRHJac2F3N24zMmtRbzFzSnVQejhmWGxldTFheURXbmtRUHluVGxLUXIvS1RRMlljSmpQbGZBdWt0bkZOQmNnPT0iLCJpYXQiOjE3NDQwMjQ2MzksImV4cCI6MTc0NDExMTAzOX0.cRgsPYQMpmrMI-qVep4MlXPHZutPqo1GDo9XxpLf034
