GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiVTJGc2RHVmtYMTl0UmMxM2NUWm9WT092QkpYeHZRK0luUEtiUEIyNWtoaktkM2tCRGFHT0lPZlZyVndHNlR5S1Q4Q1hlNlJvODlvdlphVWZVQUpHSVFKdWZVaFFxRUsvQ2ZkY1VMdy83aUVEbDcvNEhXcXJCSnZrc1kyai8yUE0wZFhMYVBSODV1RHlLRC92WTdqUmNBPT0iLCJpYXQiOjE3NDM5Mzg3NDUsImV4cCI6MTc0NDAyNTE0NX0.M6yhnK0qPeb6ML31iwQkviOH9QFSZRfR7cn8AyzMky4

###
GET http://localhost:3000/users/64d11920-0ac1-4c7c-9e4d-00d6e4d2135b
