
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username":"john",
    "phone":"0768543269",
    "email":"phantom8526@duck.com",
    "password":"1234",
    "inviteCode":"peter"
}

###


POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "phone":"0768543269",
    "password":"1234"
}